baseURL = 'https://fuxie.org/'
languageCode = 'en-us'
title = 'Fu Xie'
theme = "shiro"

[params]
  description = 'My personal website, built with Hugo.'
  github = 'https://github.com/fuxieorg/fuxie.org'
  email = 'hello@fuxie.org'
