baseURL = 'https://fuxie.org/'
languageCode = 'en-us'
title = 'Fu Xie'
theme = "shiro"
enableRobotsTXT = true

[params]
  description = 'My personal website, built with Hugo.'
  github = 'https://github.com/fuxieorg/fuxie.org'
  email = 'hello@fuxie.org'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 30

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 40

[markup]
  [markup.highlight]
    style = 'github'
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2